name: Lint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the node version your project requires

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
